### ISSUE TITLE
Add this Website! 😊

### ISSUE THREAD

**Issue by tempertemper** [calumryan/a11ywebsites#5]
__URL:__ https://www.tempertemper.net  

Martin Underhill's website meets AA standard, with many AAA success criteria also being satisfied. Care has been taken to ensure that colour contrast is met in both light and dark modes, links are underlined, focus states are very clear, and what little motion there is is removed if the user's system preferences are set to reduce motion. The code is semantic, and where this is not the case (for example, links that look like buttons), the proper semantics and behaviours have been added with ARIA, HTML attributes and JavaScript. The layout is simple, clear, and very legible, and good use is made of FS-Me, a typeface designed with accessibility in mind.

**Comment by calumryan** [comment]
Added!
